# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.project }}
  namespace: {{ .Values.namespace }}
  labels:
    app:  {{ .Values.project }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.project }}
  template:
    metadata:
      labels:
        app:  {{ .Values.project }}
    spec:
      containers:
      - name:  {{ .Values.project }}
        image:  {{ .Values.image }}:{{ .Values.tag }} 
        ports:
        - containerPort: {{ .Values.port }}
          name:  {{ .Values.project }}

